name: Publish Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: docs
    steps:
    - uses: actions/checkout@v4

    - name: Set up Erlang and Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26.0'

    - name: Install Hex and Rebar
      run: |
        mix local.hex --force
        mix local.rebar --force

    - name: Install Dependencies
      run: mix deps.get

    - name: Generate Documentation
      run: mix docs

    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
    